### ISSUE TITLE
Launcher self-updating conceptual problem

### ISSUE THREAD

**Issue by kroltan** [Troposphir/troposync#15]
# Problem
The fix for #12 included moving the project root to the system's `appData`, but this incurs a problem: If the launcher is installed in a potentially read-only directory (e.g. Windows), how will updates be applied to it?

## Suggested solution
On first run, copy all of the launcher's files from the installation directory to the `appData`, allowing the usual project sync to update it. On subsequent runs, the install-launcher delegates to the `appData`-launcher on boot.

### Pros
 - Resolves issue at hand
 - Reuses existing implementation

### Cons
 - More storage space required

Ideas, suggestions, alternatives?

**Comment by pedroslopez** [comment]
It sounds fine to me, and it's actually what I did with the current launcher. Since, on windows, there were errors while updating files inside the ProgramFiles directory, I put all the files in the ProgramData folder and just had a single file in the selected install directory that just sent all the params to the actual launcher exe.

Note that this is not necessary for macOS.

**Comment by kroltan** [comment]
Done in fd1f6a9e6d03017b0e27fd8bc1cec53c03548a89
